#!/usr/bin/env bash

cat > /etc/haproxy/haproxy.cfg <<EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend www-http
    bind *:80
    redirect scheme https code 301 if !{ ssl_fc }

frontend www-https
    bind *:443 ssl crt /etc/haproxy/certs/www.amusukwa.tech.pem
    reqadd X-Forwarded-Proto:\ https
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 407533-web-01 54.173.33.118:80 check
    server 407533-web-02 34.207.62.11:80 check
EOF

# Restart HAProxy
service haproxy restart
