#!/usr/bin/env bash

cat > /etc/haproxy/haproxy.cfg <<EOF

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        # Ensure forwarded request includes client's IP
        option forwardfor
        # Reduce latency between HAProxy and users by closing conns
        option http-server-close
        timeout connect 5000
        timeout client  50000
        timeout server  50000
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

frontend www-frontend
        bind *:80
        bind *:443 ssl crt /etc/letsencrypt/live/www.amusukwa.tech/www.amusukwa.tech.pem

        redirect scheme https code 301 if !{ ssl_fc }
        # if configuration for certbot pass to certbot backend
        acl letsencrypt-acl path_beg /.well-known/acme-challenge/
        use_backend le-certbot-backend if letsencrypt-acl

        default_backend www-backend

backend le-certbot-backend
        server letsencrypt 127.0.0.1:8888

backend www-backend
        balance roundrobin
        server 407533-web-01 54.173.33.118:80
        server 407533-web-02 34.207.62.11:80
EOF

# Restart HAProxy
service haproxy restart
