#!/usr/bin/env bash
# Update package list and install nginx

set -e

# Update package list
sudo apt-get update -y

# Install Nginx
sudo apt-get install -y nginx

# Start Nginx
sudo service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.html
