#!/usr/bin/env bash
# Update package list and install nginx

set -e

# Update package list
sudo apt-get update -y

# Install Nginx
sudo apt-get install -y nginx

sed -i 's/listen [::]:80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

cat <<EOF > /var/www/html/index.html
Hello World!

# Start Nginx
service nginx restart
