#!/usr/bin/env bash
# Update package list and install nginx
set -e

sudo apt-get update -y
sudo apt-get install -y nginx

sudo service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.html
