#!/usr/bin/env bash

# Configure your Nginx server to have a custom 404 page
sudo apt-get update
sudo apt-get install -y nginx

echo "Ceci n'est pas une page" | sudo tee /var/www/html/index.html

sudo service nginx reload
