#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a custom Nginx configuration file
echo "add_header X-Served-By \$hostname;" | sudo tee /etc/nginx/conf.d/custom_header.conf

# Restart Nginx to apply the changes
sudo service nginx restart
