#!/usr/bin/env bash
# Configures Nginx,to listen on port 80 of all the server’s active IPv4 IPs

# Install Nginx
apt-get update
apt-get install -y nginx

# Remove existing default configuration
rm /etc/nginx/sites-enabled/default

# Configure Nginx to listen on port 80
sed -i 's/8080/80/g' /etc/nginx/sites_enabled/default

# Restart Nginx to apply changes
service nginx restart
