#!/usr/bin/env bash
# Configures Nginx,to listen on port 80 of all the server’s active IPv4 IPs

# Install Nginx
apt-get update
apt-get install -y nginx

# Remove existing default configuration
rm /etc/nginx/sites-enabled/default

# Configure Nginx to listen on port 80
ln -s  /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
service nginx restart
