#!/usr/bin/env bash
# configures Nginx, to listen on port 80 of all the server’s active IPv4 IPs
rm /etc/nginx/sites-available/default
# Configure Nginx to listen on port 80
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restart Nginx to apply changes
/etc/init.d/nginx restart
