#!/usr/bin/env bash
# configures Nginx, to listen on port 80 of all the server’s active IPv4 IPs
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restart Nginx to apply changes
/etc/init.d/nginx restart
# Terminates process
kill "$(pgrep 'nginx' |head -l)"
