#!/usr/bin/env bash
#install the ufw firewall and setup a few rules on web-01

# Install ufw if not already installed
sudo apt-get update
sudo apt-get install ufw

# Set default policies
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow SSH (port 22)
sudo ufw allow 22

# Allow HTTPS (port 443)
sudo ufw allow 443

# Allow HTTP (port 80)
sudo ufw allow 80

# Enable the firewall
sudo ufw enable
